#!/usr/bin/env python3
import json
import re
import sys

OUTPUT_HEADER = f"""
/********************************************************************
 * This layout is automatically generated by {sys.argv[0]}
 ********************************************************************/

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {{
"""

OUTPUT_FOOTER = "};\n"

def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} /path/to/gergo_layout.json /path/to/output_layout.c")
    json_layout_path, output_path = sys.argv[1:]
    with open(json_layout_path) as layout_file:
        layout_json = json.load(layout_file)
    with open(output_path, "w") as output_file:
        output_file.write(OUTPUT_HEADER)
        for index, layer in enumerate(layout_json["layers"]):
            output_file.write(f"[{index}] = LAYOUT_gergo(")
            for key_index, key_code in enumerate(layer):
                if key_code.startswith("ANY("):
                    key_code = re.search('\(([^)]+)', key_code).group(1)
                output_file.write(f"{key_code}")
                if not key_index == len(layer) - 1:
                    output_file.write(", ")

            output_file.write("),\n")
        output_file.write(OUTPUT_FOOTER)


if __name__ == '__main__':
    main()
